on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  j1:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: astral-sh/setup-uv@v6.7.0
      - run: uv venv
      - run: uv pip install -r requirements.in pyspark==4.0.1
